### ISSUE TITLE
Link to onmsR

### ISSUE THREAD

**Issue by mspector13** [noaa-onms/ocnms#12]
Build out data wrangling or visualization functions specific to Sanctuary data sets in [onmsR](https://github.com/noaa-onms/onmsR)

**Note**: onmsR [still needs work](https://noaa-onms.github.io/onmsR/articles/onmsR.html)

**Comment by bbest** [comment]
This `onmsR` package is for functions to handle data wrangling and visualizations for datasets specific to the Sanctuary, whereas `infographiqR` is for functions to support generation of infographiq websites using R. I don't think we have any Sanctuary-specific datasets warranting the use of `onmsR` to incorporate here.

The exception to consider later may be the MARINe rocky intertidal datasets using functions under [Reference - Data: Rocky intertidal (MARINe) | onmsR](https://noaa-onms.github.io/onmsR/reference/index.html#section-data-rocky-intertidal-marine-).
