### ISSUE TITLE
Pull info from Gsheet w/ tabs

### ISSUE THREAD

**Issue by mspector13** [noaa-onms/ocnms#14]
Pull data from across tabs, rows, and columns in [Master_OCNMS_infographic_content](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539): 

- `scenes` 
- `modals` 
- `figures` 
- `glossary`

**Comment by bbest** [comment]
Already got the basics with modals and figures in [`render_site_v2.R`](https://github.com/noaa-onms/ocnms/blob/993aac4db69395c63f56a0b91a9b7ecf2154f701/render_site_v2.R) with:

```r
create_modals()
render_modals()
 ```

Next: `scenes`
