### ISSUE TITLE
Push/Pull: GitHub Token Authentication

### ISSUE THREAD

**Issue by mspector13** [noaa-onms/ocnms#19]
Hey @bbest, 

On August 13th GitHub implemented a token authentication for remote access (instead of just password protection).  As such, I cannot push/pull from any repo that I am **not** the owner of. 

I was able to follow [GitHub's help page](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) for token set up, and can easily generate a new token. However, when I tried to push changes to OCNMS (after getting my JSON authentication to work) I was met with an error message that unfortunately I did not screen grab. Effectively, it just said to set up a personal token using the [same link above](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token). 

Once I did that, I followed the instructions on this [3rd party's help page](https://reactgo.com/github-password-authentication-removed/) to try and set up the token in the repo itself. That has also failed. 
![Screen Shot 2021-09-08 at 3 23 35 PM](https://user-images.githubusercontent.com/59982410/132593653-2f4c3c80-8a7d-4bb4-ba6f-78511f117bc7.png). 

Perhaps I set up my token incorrectly, but regardless how does creating a token on **my** end grant me access to a repo that is under **your** name?

**Comment by bbest** [comment]
Hi Pike,

That error message suggests that git lost track of where it's supposed to update. You could try editing the configuration of the git repo on your file system:

```r
edit(file=".git/config")
```

Here's what mine looks like:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = https://github.com/noaa-onms/ocnms.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

Note that at some point we moved from `marinebon` to `noaa-onms`, which I'm guessing is your issue here.

**Comment by mspector13** [comment]
Issue was resolved in combination with adding:
 `.git` 
to  
`[remote "origin"]
	url = https://github.com/noaa-onms/ocnms` 

and by following this sequence referenced in Chapter 10 of Happy Git and [GitHub for the useR](https://happygitwithr.com/credential-caching.html#credential-caching):

`library(gitcreds)`
`gitcreds_set()`

`gitcreds_get()`
`#> <gitcreds>`
`#>   protocol: https`
`#>   host    : github.com`
`#>   username: PersonalAccessToken`
`#>   password: <-- hidden -->`

Note: a GitHub PAT was created  in Github by going to:
 `Settings` --> `Developer Settings` --> `Personal access tokens` --> `Generate new token` 
*select "repo"

In terminal: 
`git push` to test, though I was prompted to enter my computer's password via key chain access and everything *miraculously* worked
