### ISSUE TITLE
Error running dynamic figures: plot_intertidal_NMS()

### ISSUE THREAD

**Issue by mspector13** [noaa-onms/ocnms#28]
Hey @bbest , 

I can't seem to get the dynamic figures to run. When I try to run `map_nms_sites("ocnms")` (in `rocky-shore_barnacles.Rmd`) I get: 

`Error in file.exists(sites_csv) : object 'sites_csv' not found`

The issue seems to be with [`Spatial.R`](https://github.com/noaa-onms/onmsR/blob/master/R/spatial.R), which is in onmsR. 

For example, if I try to run `plot_intertidal_nms(d_csv, "OCNMS", "CHTBAL", "Acorn Barnacles") %>%
  dyLegend(show="follow")`  i get:

![Screen Shot 2022-01-18 at 12 19 11 PM](https://user-images.githubusercontent.com/59982410/150012313-b18f681b-5f97-440f-887b-2d997dd12530.png)

And with `plot_intertidal_nms(nms_spp_sscount_csv, "OCNMS", "PISOCH", "Ochre Seastar", fld_val = "count", label_y = "Count (annual avg)") %>% 
  dyLegend(show="follow")`

`Error in standardise_path(file) : object 'nms_spp_sscount_csv' not found`

**Note**: [this is affecting our automatic site build action:](https://github.com/noaa-onms/ocnms/actions/runs/1714323485) 
![Screen Shot 2022-01-18 at 12 23 48 PM](https://user-images.githubusercontent.com/59982410/150012898-090e0d79-a116-4be6-8d0b-710a258febf6.png)

**Comment by bbest** [comment]
Hey @mspector13, you need to reinstall `onmsR`. Please run:

```r
remotes::install_github("noaa-onms/onmsR")
```

**Comment by bbest** [comment]
And that other issue:

`Error in standardise_path(file) : object 'nms_spp_sscount_csv' not found`

I temporarily turned off by setting the R chunk to `eval=F`:

https://github.com/noaa-onms/ocnms/blob/9abde878d3bb0c91ae8d2bb8d2dc2eef0c946163/modals/rocky-shore_ochre-star.Rmd#L22-L27

And referenced to fix this in the separate issue #27. This has to do with a different input data file `nms_spp_sscount_csv` getting used for sea star counts (versus percent cover) that has to similarly be migrated to the new site.
