### ISSUE TITLE
Static images not loading

### ISSUE THREAD

**Issue by mspector13** [noaa-onms/ocnms#29]
Hey @bbest and @superjai 

I've been adding @bbest's `insert_caption()` function into the .Rmd files that Jai noted in the [problems spreadsheet](https://docs.google.com/spreadsheets/d/1CI7lxXOcA7uvKCpzNez-nu97EF1AIXtnVfKkdzCp0G8/edit#gid=0). As I've been going through this, I realized a lot of the modal windows I was trying to knit returned modals *without* images. I think something in `infographiqR.R` might have gotten changed. 

This is what happens when I knit one of the previously functional .Rmd files. Notice that the file path for the image has been replaced with the url to g-drive where the image is stored (before this, the name of the image file itself was placed here) 
![Screen Shot 2022-01-18 at 6 27 26 PM](https://user-images.githubusercontent.com/59982410/150053189-53a15ab1-f374-43f0-ba53-c00744b00de0.png)

This is the case for *all* of the modal windows that have static images. Any thoughts?

**Comment by bbest** [comment]
Somehow the original field `image_link` got renamed to `image_path` in the `figures` sheet of  [Master_OCNMS_infographic_content - Google Sheets](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539):

![image](https://user-images.githubusercontent.com/2837257/150058901-0faf7e3b-bb76-44b5-bb14-eb59fd0dbb67.png)

It is imperative this field be always called `image_link`. The `image_path` gets populated by `add_gimage_paths()` in `render_site.R`, so must be run every time after running `gsheets_to_csvs()`. 

https://github.com/noaa-onms/ocnms/blob/9abde878d3bb0c91ae8d2bb8d2dc2eef0c946163/render_site.R#L5-L6

I'm fixing now...
