### ISSUE TITLE
rocky-shore_mussels.Rmd: `onmsR::map_nms_sites()` -> `sites_csv` not found 

### ISSUE THREAD

**Issue by bbest** [noaa-onms/ocnms#32]
Per [latest build of render-website](https://github.com/noaa-onms/ocnms/runs/4862793390?check_suite_focus=true#step:7:876), getting error:

```
Quitting from lines 17-18 (rocky-shore_mussels.Rmd) 
Error: Error in file.exists(sites_csv) : object 'sites_csv' not found
Calls: source ... withVisible -> eval -> eval -> map_nms_sites -> file.exists
```

from unable to find `sites_csv` running:

https://github.com/noaa-onms/ocnms/blob/b69d64135597960661a4eb713bfac24a036d66a1/modals/rocky-shore_mussels.Rmd#L17

related to `onmsR::`[`map_nms_sites()`](https://noaa-onms.github.io/onmsR/reference/map_nms_sites.html).

**Comment by superjai** [comment]
@bbest - If you check out `onmsR::map_nms_sites()`, you'll see that the issue lies on this line [here](https://github.com/noaa-onms/onmsR/blob/ba39a028455c51a9607f5b2fb71df59de79f4985/R/spatial.R#L26):

```
    # BEN: note that the following line of code will fail because raw_csv and sites_csv
    # aren't defined anywhere
    if (!file.exists(sites_csv)) make_sites_csv(raw_csv, sites_csv)
```

**Comment by bbest** [comment]
## Plan

- load [MARINe_graphs.xlsx - sites in regions - Google Sheets](https://docs.google.com/spreadsheets/d/1FNYJiatsvve5lnW2Fut9Nv_AOmUaqtA0fCg8nu3Tdig/edit#gid=1616088585) into `onmsR::rocky_sites` as a lazily loaded available dataset (in `/data-raw`, `usethis::use_data(rocky_sites, overwrite = TRUE`) after adding OCNMS sites
- update other onmsR functions and OCNMS code to use  `onmsR::rocky_sites`

**Comment by mspector13** [comment]
@bbest I think we can close this issue now.
