### ISSUE TITLE
setup Zenhub board

### ISSUE THREAD

**Issue by bbest** [noaa-onms/ocnms#8]
Goal: Create big picture of Github **issues** b/n repos to get this OCNMS site done by end of September.

Here's our existing board with a bunch of repos (but without this targeted goal):
* [Board · EcoQuants/IEA/ONMS/MBON](https://app.zenhub.com/workspaces/ecoquantsieaonmsmbon-60ccc10c7de0960012e5cb14/board?repos=161368460,320333265,215839083,100316588,364402634,364047614,209862060,286868364)

Let's create a separate **Zenhub board** focused on completion of OCNMS by end of September with the **bigger vision** in mind:

1. Pull info (text, images, etc) from Google Sheet [Master_OCNMS_infographic_content](https://docs.google.com/spreadsheets/d/1C5YAp77WcnblHoIRwA_rloAagkLn0gDcJCda8E8Efu4/edit#gid=1464497539) with tabs: `scenes`, `modals`, `figures`, `glossary`.
3. Create generalizable functions in [infographiqR](https://marinebon.org/infographiqR) for applying not only to this OCNMS sanctuary, but to other sanctuaries or any infographiq website of similar design.
4. Build out any data wrangling or visualization functions specific the Sanctuaries datasets in [onmsR](https://github.com/noaa-onms/onmsR).
5. Template the `modals`.
4. Template the `scenes`.
2. Document this overall approach (esp. specific to Google Sheet tabs) in [infographiq](https://marinebon.org/infographiq).
5. Auto-update the website; see [sanctsound: `render-website.yml`](https://github.com/noaa-onms/sanctsound/actions/workflows/render-website.yml). Perhaps some diagrams would be helpful (I like Google Drawings b/c their SVG can be directly referenced: see infographiq-elements in [infographiqJS:README.md](https://raw.githubusercontent.com/marinebon/infographiqJS/main/README.md)).

Besides being able to reference repos across organizations, Zenhub has some other nice features over Github Projects:

* [Issue Dependencies using ZenHub](https://help.zenhub.com/support/solutions/articles/43000010349-create-github-issue-dependencies)
* [ZenHub Epics](https://help.zenhub.com/support/solutions/articles/43000010341-an-intro-to-zenhub-epics)

You don't need the above. Let's keep it simple to start by organizing issues:

1. Vertically in a given column by order of priority, top (highest) to bottom (lowest).
2. Horizontally across columns by sequence of time (with some thought on what depends on what)

**Comment by mspector13** [comment]
Hey @bbest, 

I made a new pipeline in Zenhub to organize/manage/strategize called **OCNMS Finish Line**

Hopefully this is what you had in mind!

**Comment by bbest** [comment]
We setup a new dedicated board and roadmap. 

## Board

[Board · OCNMS Sprint by 2021-09-20](https://app.zenhub.com/workspaces/ocnms-sprint-by-2021-09-20-6138f494e802230016436591/board?repos=161368460,215839083,100316588,364402634,364047614,209862060,286868364) with a few `noaa-onms` (`ocnms`, `onmsR`) and `marinebon` (`infographiq`, `infographiqR`, `infographiqJS`) repos added:

![image](https://user-images.githubusercontent.com/2837257/132561481-148e8f25-446b-46c2-bffc-31a50fccae87.png)

## Roadmap

After clustering the Board columns into similarly named Zenhub Epics for which we set Start and Stop dates, we added the Epics to a Project in this new [Roadmap · OCNMS Sprint by 2021-09-20](https://app.zenhub.com/workspaces/ocnms-sprint-by-2021-09-20-6138f494e802230016436591/roadmap):

![image](https://user-images.githubusercontent.com/2837257/132561984-0b902cd8-506e-4b36-8277-f3719029ba70.png)

This Roadmap can be exported for a date window as `svg`:

![image](https://user-images.githubusercontent.com/2837257/132562243-8aa9a8a0-d4c7-48d0-aa76-80242ff26338.png)

### TODO: Github Action to update public website with Roadmap progress

**Comment by bbest** [comment]
And after completing an issue we see a progress bar (dark green):

![image](https://user-images.githubusercontent.com/2837257/132563720-f30d85dc-030d-4436-b94e-43f0f542a8cb.png)

**Comment by bbest** [comment]
Ok, so what's our best streamlined use of:

- **Epics** (beg, end): show up in **Roadmaps** (answer the _**manager Q**_  "how's the project going?")
- **Pipelines** (name, horizontal order): Kanban; good for detailed prioritization -- i.e., answer the _**developer Q**_ "what should I work on next?"

Skip for now:
- **Milestones** (end): native to Github

To investigate further:
- **Sprints**
